version: '3.5'
services:
  aws-gd:
    image: docker.frcpnt.com/fp-dim/fp-awsgd:latest
    environment:
      INTERNAL_TOKEN: JQnDht6Ef3zfzH7assCzdW
      HOST_DOMAIN: localhost
      CONTROLLER_SVC_NAME: dim-controller
      CONTROLLER_PORT: 8080
      MODULE_SVC_NAME: aws-gd
      LOCAL_PORT: 8080
    restart: always
    volumes:
    - ${PWD}/config:/config
    networks:
      - fp-dim-controller_module-net

networks:
  fp-dim-controller_module-net:
    external: true
